ZETA_HOME = ../../..
include Makefile.shared
ALREADY_CACHED_LIST='*,-Zeta.Steel.ApplicationRecord,-Zeta.Formats,+Zeta.Formats.Aux,-Zeta.Formats.Aux.External,-Zeta.Formats.Aux.Significant_digits_t,-Zeta.Formats.Aux.Application_key,-Zeta.Formats.Aux.Application_value,-Zeta.Formats.Aux.Internal_key,-Zeta.Steel.FormatsManual.Spec,-Zeta.Formats.LogEntry,-Zeta.Steel.LogEntry.Spec'

all: verify

include $(ZETA_HOME)/Makefile.common
