ZETA_HOME = ../../..
include ../spec/Makefile.shared
SRC_DIRS += $(ZETA_STEEL_FORMATS_HOME)/spec $(ZETA_HOME)/_output/cache
OUTPUT_DIRECTORY ?= _output
ALREADY_CACHED_LIST='*,-Zeta.LowStar'

all: verify

include $(ZETA_HOME)/Makefile.common
