ARG EVEREST_TAG=latest
FROM projecteverest/everest-linux:$EVEREST_TAG

ADD --chown=test:test . veritas
ARG CI_THREADS=16
ENV FSTAR_HOME="$HOME/FStar"
ENV KRML_HOME="$HOME/karamel"
ENV EVERPARSE_HOME="$HOME/everparse"
RUN make -C veritas -j $CI_THREADS ci
