# This Dockerfile should be run from the root Zeta directory

ARG STEEL_BRANCH=main
FROM steel:local-branch-$STEEL_BRANCH

# FIXME: the Steel repository Dockerfile should export this variable
ENV STEEL_HOME=$HOME/steel

ADD --chown=opam:opam ./ $HOME/zeta/

# CI proper
WORKDIR $HOME/zeta
RUN eval $(opam env) && make -j $CI_THREADS ci && git diff --exit-code
