ZETA_HOME = ../../..
include ../spec/Makefile.shared
SRC_DIRS += $(ZETA_STEEL_FORMATS_HOME)/spec
ALREADY_CACHED_LIST='*,-Zeta.Steel.FormatsLib,-Zeta.Steel.LogEntry,+Zeta.Steel.LogEntry.Spec,+Zeta.Steel.LogEntry.Types,-Zeta.Steel.FormatsManual,+Zeta.Steel.FormatsManual.Spec'

all: verify

include $(ZETA_HOME)/Makefile.common
