# every app subdirectory makefile should set ZETA_HOME before including this

# get all the source directories
include $(ZETA_HOME)/steel/Makefile.shared

# other common stuff
include $(ZETA_HOME)/Makefile.common

