all: makefileobj

.PHONY: all makefileobj

include Makefile.include

makefileobj: $(QD_TARGET_DIR)/Makefile

$(QD_TARGET_DIR)/Makefile: Makefile.obj Zeta.Formats.rfc
	mkdir -p $(QD_TARGET_DIR)
	$(QD) -odir $(QD_TARGET_DIR) Zeta.Formats.rfc -types_to $(FORMATS_HOME)/Zeta.Formats.Types.fst -prefix Zeta.Formats.EverParse.
	cp $< $@
