ZETA_HOME=../../../..
include $(ZETA_HOME)/steel/formats/spec/Makefile.shared
SRC_DIRS += .. $(ZETA_STEEL_FORMATS_HOME)/spec $(ZETA_STEEL_FORMATS_HOME)/lowstar $(ZETA_STEEL_FORMATS_HOME)/lowstar/_output/cache
APP_DIST_DIRECTORY=../dist
OUTPUT_DIRECTORY=../_output
ALREADY_CACHED_LIST = '*,-Zeta.KeyValueStore.Formats.Spec,-Zeta.KeyValueStore.Formats.LowStar'
KRML_BUNDLE_ROOT=Zeta.KeyValueStore.Formats.LowStar
KRML_BUNDLING_OPTIONS=-no-prefix Zeta.KeyValueStore.Formats.LowStar
include ../../Makefile
