ZETA_HOME=../../../..
include $(ZETA_HOME)/steel/formats/spec/Makefile.shared
SRC_DIRS += .. $(ZETA_STEEL_FORMATS_HOME)/lowstar
APP_DIST_DIRECTORY=../dist
OUTPUT_DIRECTORY=../_output

include ../../Makefile
