all: makefileobj

.PHONY: all makefileobj

include Makefile.include

makefileobj: $(QD_TARGET_DIR)/Makefile

$(QD_TARGET_DIR)/Makefile: Makefile.obj Zeta.Formats.Aux.rfc
	mkdir -p $(QD_TARGET_DIR)
	$(QD) -odir $(QD_TARGET_DIR) Zeta.Formats.Aux.rfc -prefix Zeta.Formats.Aux.
	cp $< $@
