on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file .ci/Dockerfile.everest-hub --build-arg CI_THREADS=4 --build-arg EVEREST_TAG=commit-2a2020a5c67b07e7ec621cb7f836a0e53578b439
