name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '1 4,10,16,22 * * *'

jobs:

  build:

    runs-on: [self-hosted, linux, X64]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --no-cache --file .ci/Dockerfile.everparse
