on: [push, pull_request]

jobs:

  build:

    runs-on: [self-hosted, linux, X64]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file .ci/Dockerfile.steel
